#!/usr/bin/env python3
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from ui.application import VpnApp

if __name__ == "__main__":
    app = VpnApp()
    app.run(None)
